pipeline{
        agent any
        stages{
        stage('stage1'){
         steps{
         sh 'echo this is stage 1'
          }
       }
      stage('stage2'){
       steps{
       sh 'echo from stage2'
        }
      }
   }

}
