pipeline{
        agent any
        stages{
        stage('stage1'){
         steps{
         sh 'echo this is from the stage 1'
          }
       }
      stage('stage2'){
       steps{
       sh 'echo this is from the stage2'
        }
      }
   }

}
